#ifndef 1_h_
#define 1_h_

#include <avr/pgmspace.h>
#include <inttypes.h>

/**
 * autogenerated lookup function for MyFavoriteSensor
 * @param i     x value
 * @return      f(i), or 6666 if i is out of range
 */
uint16_t lookup_MyFavoriteSensor(uint16_t i);

#endif /* 1_h_ */

