#ifndef klin_h_
#define klin_h_

#include <avr/pgmspace.h>
#include <inttypes.h>

/**
 * autogenerated lookup function for Daumengas
 * @param i     x value
 * @return      f(i), or 6666 if i is out of range
 */
uint16_t lookup_Daumengas(uint16_t i);

#endif /* klin_h_ */

